on:
  push:
    branches: ["main", "develop", "cicd"]
  pull_request:
    branches: ["main", "develop", "cicd"]

jobs:
  reusable_workflow_job:
    uses: ./.github/workflows/unitTests.yml
    name: My first step

