name: main

on:
  push:
    branches: ["main", "develop", "cicd"]
  pull_request:
    branches: ["main", "develop", "cicd"]

defaults:
  run:
    working-directory: ./Juntos

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
  

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: Juntos/package-lock.json

      - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Continue with Firebase Hosting
        if: always()
        uses: peter-evans/repository-dispatch@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
          repository: LemonKvas/juntos-events-ip2
          event-type: startFirebaseHosting

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        if: always()
        run: npm run lint-and-fix

      - name: Unit Tests
        if: always()
        run: npm run test






