on:
  push:
    branches: ["main", "develop", "cicd"]
  pull_request:
    branches: ["main", "develop", "cicd"]

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: My first step
      uses: ./.github/workflows/unitTests

